function projectShutdown()
    
    thisProject = slproject.getCurrentProject;
    rootFolder  = thisProject.RootFolder;
    
    removeProjectPath;
    
    cd(rootFolder);
    
    % If you modified the root folders in which to put files generated by
    % diagram updates and model builds, reset to the settings in Simulink
    % Preferences.
    % Simulink.fileGenControl('reset', 'keepPreviousPath', true)

    
end


